### PR TITLE
Release notes for 2022.10

### PR DESCRIPTION
**Pull request by timmiesmith**
The oneDPL release for the 2022.10.0 milestone covers roughly the changes from merged PRs #2207 to #2465.

### CODE REVIEW

File: documentation/release_notes.rst [hunk 1]
```diff
@@ -11,14 +11,74 @@ creating efficient heterogeneous applications.
...
+- Fixed ``equal`` returning a ``false`` for empty input sequences; now it returns ``true``.
+- Fixed a compilation error **SYCL kernel cannot use exceptions** occurring with libstdc++ version 10 when calling
+  range-based ``adjacent_find``, ``is_sorted`` and ``is_sorted_until`` algorithms using  device policies.
+- Fixed an issue with ``PSTL_USE_NONTEMPORAL_STORES`` macro having no effect.
+- Fixed a bug where ``oneapi::dpl::unique`` when called with a device execution policy returned an incorrect result
+  iterator.
+- Fixed a bug in ``oneapi::dpl::inclusive_scan`` and all prefix sum algorithms when using device policies with differing
+  ``InputIterator`` and ``OutputIterator`` types.
+- Fixed error in return value types for oneapi::dpl::ranges::minmax_element and oneapi::dpl::ranges::mismatch algorithms.
+- Fixed compile errors in ``oneapi::dpl::set_union`` and ``oneapi::dpl::set_symmetric_difference`` for hetero execution
```
Comment (timmiesmith) [inline documentation/release_notes.rst]: @SergeyKopienko were the compile errors introduced in #2318? If so they weren't present in a previous release and I don't think need to be mentioned here.

File: documentation/release_notes.rst [hunk 2]
```diff
@@ -11,14 +11,74 @@ creating efficient heterogeneous applications.
...
+  ``set_difference``, ``set_symmetric_difference``, ``includes``, ``unique``, ``unique_copy``, ``destroy``,
+  ``uninitialized_fill``, ``uninitialized_move``, ``uninitialized_copy``, ``uninitialized_value_construct``,
+  ``uninitialized_default_construct``, ``reverse``, ``reverse_copy``, ``swap_ranges``. These algorithms operate with
+  C++20 random access ranges.
+- Improved performance of ``oneapi::dpl::experimental::kt::gpu::inclusive_scan`` and added support for binary operator
+  and type combinations which do not have a SYCL known identity.
+- Improved performance of ``oneapi::dpl::inclusive_scan_by_segment ``and ``oneapi::dpl::exclusive_scan_by_segment`` with
+  device execution policies on GPUs.
+- Improved performance of set operation algorithms when using device policies: ``set_union``, ``set_difference``,
+  ``set_intersection``, ``set_symmetric_difference``. Removed default constructible requirements from value type of
```
Comment (timmiesmith) [inline documentation/release_notes.rst]: @danhoeflinger your suggestion to combine the note for #2318 and #2354 feels awkward since the first is performance focused and the second is relaxing the requirements on the parameters passed to the algorithms.  Should they be split into two items?

File: documentation/release_notes.rst [hunk 3]
```diff
@@ -11,14 +11,74 @@ creating efficient heterogeneous applications.
...
+^^^^^^^^^^^^^^^
+See oneDPL Guide for other `restrictions and known limitations`_.
+
+- Range-based ``copy_if``, ``unique_copy``, ``set_union``, ``set_intersection``, ``set_difference``,
+  ``set_symmetric_difference`` algorithms require the output range to have sufficient size to hold all resulting
+  elements.
+- ``histogram`` algorithm requires the output value type to be an integral type no larger than four bytes
+  when used with a device policy on hardware that does not support 64-bit atomic operations.
+- ``histogram`` may provide incorrect results with device policies in a program built with ``-O0`` option and the driver
+  version is 2448.13 or older.
```
Comment (dmitriy-sobolev) [inline documentation/release_notes.rst]: `2448.13` is a no longer supported Rolling driver. Let's remove this note.

File: documentation/release_notes.rst [hunk 4]
```diff
@@ -11,14 +11,74 @@ creating efficient heterogeneous applications.
...
+------------
+- Fixed an issue with incorrect handling of different projections by range-based ``merge``.
+- Fixed ``equal`` returning a ``false`` for empty input sequences; now it returns ``true``.
+- Fixed a compilation error **SYCL kernel cannot use exceptions** occurring with libstdc++ version 10 when calling
+  range-based ``adjacent_find``, ``is_sorted`` and ``is_sorted_until`` algorithms using  device policies.
+- Fixed an issue with ``PSTL_USE_NONTEMPORAL_STORES`` macro having no effect.
+- Fixed a bug where ``oneapi::dpl::unique`` when called with a device execution policy returned an incorrect result
+  iterator.
+- Fixed a bug in ``oneapi::dpl::inclusive_scan`` and all prefix sum algorithms when using device policies with differing
+  ``InputIterator`` and ``OutputIterator`` types.
```
Comment (dmitriy-sobolev) [inline documentation/release_notes.rst]: Let's list all prefix sum algorithms. It may not be obvious what it includes.

File: documentation/release_notes.rst [hunk 5]
```diff
@@ -11,14 +11,74 @@ creating efficient heterogeneous applications.
...
+  ``uninitialized_default_construct``, ``reverse``, ``reverse_copy``, ``swap_ranges``. These algorithms operate with
+  C++20 random access ranges.
+- Improved performance of ``oneapi::dpl::experimental::kt::gpu::inclusive_scan`` and added support for binary operator
+  and type combinations which do not have a SYCL known identity.
+- Improved performance of ``oneapi::dpl::inclusive_scan_by_segment ``and ``oneapi::dpl::exclusive_scan_by_segment`` with
+  device execution policies on GPUs.
+- Improved performance of set operation algorithms when using device policies: ``set_union``, ``set_difference``,
+  ``set_intersection``, ``set_symmetric_difference``. Removed default constructible requirements from value type of
+  reduce and transform_reduce when used with an execution policy.
+- Improved performance of parallel_find_or–based algorithms on Intel® Arc™ B-series GPU devices.
```
Comment (dmitriy-sobolev) [inline documentation/release_notes.rst]: Let's list these algorithms all or only a portion if there are too many of them. `parallel_find_or–based` is super unobvious to a non-developer.

File: documentation/release_notes.rst [hunk 6]
```diff
@@ -11,14 +11,74 @@ creating efficient heterogeneous applications.
...
+------------
+- Added parallel range algorithms in ``namespace oneapi::dpl::ranges``: ``set_intersection``, ``set_union``,
+  ``set_difference``, ``set_symmetric_difference``, ``includes``, ``unique``, ``unique_copy``, ``destroy``,
+  ``uninitialized_fill``, ``uninitialized_move``, ``uninitialized_copy``, ``uninitialized_value_construct``,
+  ``uninitialized_default_construct``, ``reverse``, ``reverse_copy``, ``swap_ranges``. These algorithms operate with
+  C++20 random access ranges.
+- Improved performance of ``oneapi::dpl::experimental::kt::gpu::inclusive_scan`` and added support for binary operator
+  and type combinations which do not have a SYCL known identity.
+- Improved performance of ``oneapi::dpl::inclusive_scan_by_segment ``and ``oneapi::dpl::exclusive_scan_by_segment`` with
+  device execution policies on GPUs.
```
Comment (dmitriy-sobolev) [inline documentation/release_notes.rst]: Fixing spaces. Also removing the `oneapi::dpl` namespace for consistency - it's not specified with other algorithms from this namespace.

```suggestion
- Improved performance of ``inclusive_scan_by_segment`` and ``exclusive_scan_by_segment`` with
  device execution policies on GPUs.
```

There are other places with the namespaces.

File: documentation/release_notes.rst (hunk 2 above)
Comment (danhoeflinger) [reply documentation/release_notes.rst]: Sorry I wrote the wrong number,  I meant to combine it with #2355 which discusses other requirements for the value type of [transform_]reduce.

File: documentation/release_notes.rst (hunk 1 above)
Comment (danhoeflinger) [reply documentation/release_notes.rst]: I think they predate #2318, but @SergeyKopienko  should weigh in.

File: documentation/release_notes.rst (hunk 3 above)
Comment (timmiesmith) [reply documentation/release_notes.rst]: Done.

File: documentation/release_notes.rst (hunk 2 above)
Comment (timmiesmith) [reply documentation/release_notes.rst]: I've moved the comment.

File: documentation/release_notes.rst [hunk 7]
```diff
@@ -11,14 +11,71 @@ creating efficient heterogeneous applications.
...
+  and type combinations which do not have a SYCL known identity.
+- Improved performance of ``inclusive_scan_by_segment`` and ``exclusive_scan_by_segment`` with
+  device execution policies on GPUs.
+- Improved performance of set operation algorithms when using device policies: ``set_union``, ``set_difference``,
+  ``set_intersection``, ``set_symmetric_difference``.
+- Improved performance of parallel_find_or–based algorithms on Intel® Arc™ B-series GPU devices.
+- Removed requirement of GPU double support to use ``set_union``, ``set_difference``, ``set_intersection``, and
+  ``set_symmetric_difference`` on Windows operating systems.
+- Removed copy constructible requirements from value type for reduce and transform_reduce algorithms when used with a
+  host policy, and default constructible requirements from value type for reduce and transform_reduce when used with an execution policy.
```
Comment (timmiesmith) [inline documentation/release_notes.rst]: @danhoeflinger at the end of the line here is "an execution policy" a host or device policy?  Is it any policy?

File: documentation/release_notes.rst (hunk 4 above)
Comment (timmiesmith) [reply documentation/release_notes.rst]: Done.

File: documentation/release_notes.rst (hunk 5 above)
Comment (timmiesmith) [reply documentation/release_notes.rst]: [83d4484](https://github.com/uxlfoundation/oneDPL/pull/2483/commits/83d448421a18728ececed3301dec96c3ba3a8d0b) lists all of the algorithms.  I think this is too much detail.  What I have in the notes now refers to the algorithms as "search algorithms" and the ``is_heap`` algorithms, which is the algorithm class from the C++ standard, to make the line more concise.

File: documentation/release_notes.rst (hunk 7 above)
Comment (timmiesmith) [reply documentation/release_notes.rst]: After offline discussion fixing this to indicate all policies are impacted.

File: documentation/release_notes.rst [hunk 8]
```diff
@@ -11,14 +11,74 @@ creating efficient heterogeneous applications.
...
+release. Please use the relevant compiler flags to enable this feature.
+
+New Features
+------------
+- Added parallel range algorithms in ``namespace oneapi::dpl::ranges``: ``set_intersection``, ``set_union``,
+  ``set_difference``, ``set_symmetric_difference``, ``includes``, ``unique``, ``unique_copy``, ``destroy``,
+  ``uninitialized_fill``, ``uninitialized_move``, ``uninitialized_copy``, ``uninitialized_value_construct``,
+  ``uninitialized_default_construct``, ``reverse``, ``reverse_copy``, ``swap_ranges``. These algorithms operate with
+  C++20 random access ranges.
+- Improved performance of ``oneapi::dpl::experimental::kt::gpu::inclusive_scan`` and added support for binary operator
```
Comment (mmichel11) [inline documentation/release_notes.rst]: Since we've removed the `oneapi::dpl` namespace for other cases, do we just want to refer to this as "`inclusive_scan` kernel template" or keep the full namespace?

File: documentation/release_notes.rst [hunk 9]
```diff
@@ -11,14 +11,74 @@ creating efficient heterogeneous applications.
...
+- Fixed ``equal`` returning a ``false`` for empty input sequences; now it returns ``true``.
+- Fixed a compilation error **SYCL kernel cannot use exceptions** occurring with libstdc++ version 10 when calling
+  range-based ``adjacent_find``, ``is_sorted`` and ``is_sorted_until`` algorithms using  device policies.
+- Fixed an issue with ``PSTL_USE_NONTEMPORAL_STORES`` macro having no effect.
+- Fixed a bug where ``unique`` when called with a device execution policy returned an incorrect result
+  iterator.
+- Fixed a bug in ``exclusive_scan``, ``inclusive_scan``, ``transform_exclusive_scan``, ``transform_inclusive_scan``,
+  ``exlusive_scan_by_segment``, and ``inclusive_scan_by_segment`` algorithms when using device policies with differing
+  ``InputIterator`` and ``OutputIterator`` types.
+- Fixed error in return value types for oneapi::dpl::ranges::minmax_element and oneapi::dpl::ranges::mismatch algorithms.
```
Comment (mmichel11) [inline documentation/release_notes.rst]:
```suggestion
- Fixed error in return value types of range-based ``minmax_element`` and ``mismatch`` algorithms.
```

File: documentation/release_notes.rst [hunk 10]
```diff
@@ -11,14 +11,74 @@ creating efficient heterogeneous applications.
...
+- Fixed compile errors in ``set_union`` and ``set_symmetric_difference`` for hetero execution policies when the types of
```
Comment (mmichel11) [inline documentation/release_notes.rst]: I think instead of hetero we've used the term device execution policies more commonly.
```suggestion
- Fixed compile errors in ``set_union`` and ``set_symmetric_difference`` with device execution policies when the types of
```

File: documentation/release_notes.rst [hunk 11]
```diff
@@ -11,14 +11,74 @@ creating efficient heterogeneous applications.
...
+
 Known Issues and Limitations
 ----------------------------
 New in This Release
 ^^^^^^^^^^^^^^^^^^^
-- Calling ``histogram`` algorithm with a device execution policy may cause a segmentation fault in
-  Intel® oneAPI DPC++/C++ Compiler 2025.3 when compiling SYCL kernels for CPU devices.
-  To avoid this, define ``ONEDPL_DISABLE_HISTOGRAM_REGISTER_REDUCTION`` macro to a non-zero value
-  prior to including oneDPL header files.
+- The `set_intersection`, `set_difference`, `set_symmetric_difference`, and `set_union` algorithms with a device policy
```
Comment (mmichel11) [inline documentation/release_notes.rst]: I think this was accidentally copied here from the new issues section in the last release. We have the following note above saying it is fixed, "Removed requirement of GPU double support to use ``set_union``, ``set_difference``, ``set_intersection``, and ``set_symmetric_difference`` on Windows operating systems.".

**Review by mmichel11 — COMMENTED** [review]
Everything else LGTM.

File: documentation/release_notes.rst
Comment (SergeyKopienko) [inline documentation/release_notes.rst]: We should note about new range algorithms that they are not support limited output-range size for now.

File: documentation/release_notes.rst (hunk 8 above)
Comment (akukanov) [reply documentation/release_notes.rst]: I would use "``gpu::inclusive_scan`` kernel template", as we did for ``radix_sort`` notes before

File: documentation/release_notes.rst [hunk 12]
```diff
@@ -11,14 +11,74 @@ creating efficient heterogeneous applications.
...
+  ``set_difference``, ``set_symmetric_difference``, ``includes``, ``unique``, ``unique_copy``, ``destroy``,
+  ``uninitialized_fill``, ``uninitialized_move``, ``uninitialized_copy``, ``uninitialized_value_construct``,
+  ``uninitialized_default_construct``, ``reverse``, ``reverse_copy``, ``swap_ranges``. These algorithms operate with
+  C++20 random access ranges.
+- Improved performance of ``oneapi::dpl::experimental::kt::gpu::inclusive_scan`` and added support for binary operator
+  and type combinations which do not have a SYCL known identity.
+- Improved performance of ``inclusive_scan_by_segment`` and ``exclusive_scan_by_segment`` with
+  device execution policies on GPUs.
+- Improved performance of set operation algorithms when using device policies: ``set_union``, ``set_difference``,
+  ``set_intersection``, ``set_symmetric_difference``.
```
Comment (akukanov) [inline documentation/release_notes.rst]: Is there a good reason not to combine these two notes?

File: documentation/release_notes.rst [hunk 13]
```diff
@@ -11,14 +11,74 @@ creating efficient heterogeneous applications.
...
+- Improved performance of search operations (e.g., ``find``, ``all_of``, ``equal``, ``search``, etc.), ``is_heap`` and
+  ``is_heap_until`` algorithms on Intel® Arc™ B-series GPU devices.
+- Removed requirement of GPU double support to use ``set_union``, ``set_difference``, ``set_intersection``, and
+  ``set_symmetric_difference`` on Windows operating systems.
+- Removed copy constructible requirements from value type for ``reduce`` and ``transform_reduce`` algorithms when used
+  with a host policy, and default constructible requirements from value type for ``reduce`` and ``transform_reduce``
+  when used with any execution policy.
```
Comment (akukanov) [inline documentation/release_notes.rst]: Maybe move these notes into "Fixed issues"?

File: documentation/release_notes.rst [hunk 14]
```diff
@@ -11,14 +11,74 @@ creating efficient heterogeneous applications.
...
+- The `set_intersection`, `set_difference`, `set_symmetric_difference`, and `set_union` algorithms with a device policy
+require GPUs with double-precision support on Windows, regardless of the value type of the input sequences.
+
+Existing Issues
+^^^^^^^^^^^^^^^
+See oneDPL Guide for other `restrictions and known limitations`_.
+
+- Range-based ``copy_if``, ``unique_copy``, ``set_union``, ``set_intersection``, ``set_difference``,
+  ``set_symmetric_difference`` algorithms require the output range to have sufficient size to hold all resulting
+  elements.
```
Comment (akukanov) [inline documentation/release_notes.rst]: Except for `copy_if`, this is a new issue.

File: documentation/release_notes.rst
Comment (akukanov) [reply documentation/release_notes.rst]: There is a note on this, but in the "Existing issues", which seems to be a mistake: https://github.com/uxlfoundation/oneDPL/pull/2483#discussion_r2381951509

File: documentation/release_notes.rst (hunk 12 above)
Comment (danhoeflinger) [reply documentation/release_notes.rst]: Seems like they can be combined.

File: documentation/release_notes.rst [hunk 15]
```diff
@@ -11,14 +11,74 @@ creating efficient heterogeneous applications.
...
+- Fixed an issue with incorrect handling of different projections by range-based ``merge``.
+- Fixed ``equal`` returning a ``false`` for empty input sequences; now it returns ``true``.
+- Fixed a compilation error **SYCL kernel cannot use exceptions** occurring with libstdc++ version 10 when calling
+  range-based ``adjacent_find``, ``is_sorted`` and ``is_sorted_until`` algorithms using  device policies.
+- Fixed an issue with ``PSTL_USE_NONTEMPORAL_STORES`` macro having no effect.
+- Fixed a bug where ``unique`` when called with a device execution policy returned an incorrect result
+  iterator.
+- Fixed a bug in ``exclusive_scan``, ``inclusive_scan``, ``transform_exclusive_scan``, ``transform_inclusive_scan``,
+  ``exlusive_scan_by_segment``, and ``inclusive_scan_by_segment`` algorithms when using device policies with differing
+  ``InputIterator`` and ``OutputIterator`` types.
```
Comment (danhoeflinger) [inline documentation/release_notes.rst]: Is it differing iterator types or differing iterator value types?

Comment (mmichel11) [reply documentation/release_notes.rst]: Good catch, it should be, "differing ``InputIterator`` and ``OutputIterator`` value types"

File: documentation/release_notes.rst (hunk 8 above)
Comment (timmiesmith) [reply documentation/release_notes.rst]: I've made this change.

File: documentation/release_notes.rst (hunk 11 above)
Comment (timmiesmith) [reply documentation/release_notes.rst]: Fixed.

File: documentation/release_notes.rst (hunk 15 above)
Comment (timmiesmith) [reply documentation/release_notes.rst]: Fixed.

File: documentation/release_notes.rst
Comment (timmiesmith) [reply documentation/release_notes.rst]: It was noted that ``copy_if`` has been noted for this issue previously.  Should we leave it in the existing issues section and create a new entry for the rest, or would it be ok to keep a single entry and move it to the New Issues section?

File: documentation/release_notes.rst (hunk 12 above)
Comment (timmiesmith) [reply documentation/release_notes.rst]: Fixed.

File: documentation/release_notes.rst (hunk 13 above)
Comment (timmiesmith) [reply documentation/release_notes.rst]: Done.

File: documentation/release_notes.rst (hunk 14 above)
Comment (timmiesmith) [reply documentation/release_notes.rst]: I see that ``copy_if`` wasn't noted in previous release notes either, so I'll move the entire comment to the "New Issues" section.

File: documentation/release_notes.rst
Comment (timmiesmith) [reply documentation/release_notes.rst]: I've moved the note to the correct section.

File: documentation/release_notes.rst (hunk 1 above)
Comment (SergeyKopienko) [reply documentation/release_notes.rst]: I am not faced with compile errors introduced in #2318. I just fixed some potentially problem places about types which describes sizes, as far as I remember.

File: documentation/release_notes.rst [hunk 16]
```diff
@@ -11,14 +11,70 @@ creating efficient heterogeneous applications.
...
+------------
+- Added parallel range algorithms in ``namespace oneapi::dpl::ranges``: ``set_intersection``, ``set_union``,
+  ``set_difference``, ``set_symmetric_difference``, ``includes``, ``unique``, ``unique_copy``, ``destroy``,
+  ``uninitialized_fill``, ``uninitialized_move``, ``uninitialized_copy``, ``uninitialized_value_construct``,
+  ``uninitialized_default_construct``, ``reverse``, ``reverse_copy``, ``swap_ranges``. These algorithms operate with
+  C++20 random access ranges.
+- Improved performance of ``gpu::inclusive_scan`` kernel template and added support for binary operator and type
+  combinations which do not have a SYCL known identity.
+- Improved performance of ``inclusive_scan_by_segment``, ``exclusive_scan_by_segment`` and set operation algorithms when
+  using device policies: ``set_union``, ``set_difference``, ``set_intersection``, ``set_symmetric_difference``.
```
Comment (danhoeflinger) [inline documentation/release_notes.rst]: [nitpick] 
The formulation of this sentence is a bit strange.
```suggestion
- Improved performance of scan_by_segment and set operation algorithms when
  using device policies: ``inclusive_scan_by_segment``, ``exclusive_scan_by_segment``, ``set_union``, ``set_difference``, ``set_intersection``, ``set_symmetric_difference``.
```

Or alternatively, just list the algorithms out without other commentary:
``` 
- Improved performance of ``inclusive_scan_by_segment``, ``exclusive_scan_by_segment``, ``set_union``, ``set_difference``, ``set_intersection``, and ``set_symmetric_difference`` algorithms when
  using device policies.
```

Comment (timmiesmith) [reply documentation/release_notes.rst]: Separating the set operation algorithms out with the colon is odd even with the suggestion.  I've just listed the algorithms as you suggest.

**Review by mmichel11 — DISMISSED** [review]
LGTM

**Review by danhoeflinger — APPROVED** [review]
LGTM

File: documentation/release_notes.rst [hunk 17]
```diff
@@ -11,14 +11,70 @@ creating efficient heterogeneous applications.
...
+  range-based ``adjacent_find``, ``is_sorted`` and ``is_sorted_until`` algorithms using  device policies.
+- Fixed an issue with ``PSTL_USE_NONTEMPORAL_STORES`` macro having no effect.
+- Fixed a bug where ``unique`` when called with a device execution policy returned an incorrect result
+  iterator.
+- Fixed a bug in ``exclusive_scan``, ``inclusive_scan``, ``transform_exclusive_scan``, ``transform_inclusive_scan``,
+  ``exlusive_scan_by_segment``, and ``inclusive_scan_by_segment`` algorithms when using device policies with differing
+  ``InputIterator`` and ``OutputIterator`` value types.
+- Fixed error in return value types of range-based ``minmax_element`` and ``mismatch`` algorithms.
+- Fixed compile errors in ``set_union`` and ``set_symmetric_difference`` with device execution policies when the types of
+  the second data and results data are different.
```
Comment (akukanov) [inline documentation/release_notes.rst]:
```suggestion
- Fixed a bug in return value types of ``minmax_element`` and ``mismatch`` range algorithms.
- Fixed compile errors in ``set_union`` and ``set_symmetric_difference`` when using device policies
  with different second-input and output value types.
```

"Range-based" is a term I would like to gradually replace, because in the specification and documentation we primarily use "[parallel] range algorithms".

File: documentation/release_notes.rst [hunk 18]
```diff
@@ -11,14 +11,70 @@ creating efficient heterogeneous applications.
...
 ----------------------------
 New in This Release
 ^^^^^^^^^^^^^^^^^^^
-- Calling ``histogram`` algorithm with a device execution policy may cause a segmentation fault in
-  Intel® oneAPI DPC++/C++ Compiler 2025.3 when compiling SYCL kernels for CPU devices.
-  To avoid this, define ``ONEDPL_DISABLE_HISTOGRAM_REGISTER_REDUCTION`` macro to a non-zero value
-  prior to including oneDPL header files.
+- Range-based ``copy_if``, ``unique_copy``, ``set_union``, ``set_intersection``, ``set_difference``,
+  ``set_symmetric_difference`` algorithms require the output range to have sufficient size to hold all resulting
+  elements.
```
Comment (akukanov) [inline documentation/release_notes.rst]:
```suggestion
- ``copy_if``, ``unique_copy``, ``set_union``, ``set_intersection``, ``set_difference``, ``set_symmetric_difference``
  range algorithms require the output range to have sufficient size to hold all resulting elements.
```

File: documentation/release_notes.rst [hunk 19]
```diff
@@ -11,14 +11,70 @@ creating efficient heterogeneous applications.
...
+  ``is_heap_until`` algorithms on Intel® Arc™ B-series GPU devices.
+
+Fixed Issues
+------------
+- Removed requirement of GPU double support to use ``set_union``, ``set_difference``, ``set_intersection``, and
+  ``set_symmetric_difference`` on Windows operating systems.
+- Removed copy constructible requirements from value type for ``reduce`` and ``transform_reduce`` algorithms when used
+  with a host policy, and default constructible requirements from value type for ``reduce`` and ``transform_reduce``
+  when used with any execution policy.
+- Fixed an issue with incorrect handling of different projections by range-based ``merge``.
```
Comment (akukanov) [inline documentation/release_notes.rst]:
```suggestion
- Fixed an issue with incorrect handling of different projections by ``ranges::merge``.
```

File: documentation/release_notes.rst [hunk 20]
```diff
@@ -11,14 +11,70 @@ creating efficient heterogeneous applications.
...
+- Fixed ``equal`` returning a ``false`` for empty input sequences; now it returns ``true``.
+- Fixed a compilation error **SYCL kernel cannot use exceptions** occurring with libstdc++ version 10 when calling
+  range-based ``adjacent_find``, ``is_sorted`` and ``is_sorted_until`` algorithms using  device policies.
```
Comment (akukanov) [inline documentation/release_notes.rst]:
```suggestion
- Fixed a compilation error **SYCL kernel cannot use exceptions** occurring with libstdc++ version 10 when calling
  ``adjacent_find``, ``is_sorted`` and ``is_sorted_until`` range algorithms with device policies.
```

File: documentation/release_notes.rst [hunk 21]
```diff
@@ -11,14 +11,70 @@ creating efficient heterogeneous applications.
...
+- Fixed an issue with ``PSTL_USE_NONTEMPORAL_STORES`` macro having no effect.
+- Fixed a bug where ``unique`` when called with a device execution policy returned an incorrect result
+  iterator.
```
Comment (akukanov) [inline documentation/release_notes.rst]:
```suggestion
- Fixed a bug where ``unique`` called with a device policy returned an incorrect result iterator.
```

File: documentation/release_notes.rst [hunk 22]
```diff
@@ -11,14 +11,70 @@ creating efficient heterogeneous applications.
...
+- Fixed a bug in ``exclusive_scan``, ``inclusive_scan``, ``transform_exclusive_scan``, ``transform_inclusive_scan``,
+  ``exlusive_scan_by_segment``, and ``inclusive_scan_by_segment`` algorithms when using device policies with differing
+  ``InputIterator`` and ``OutputIterator`` value types.
```
Comment (akukanov) [inline documentation/release_notes.rst]:
```suggestion
- Fixed a bug in ``exclusive_scan``, ``inclusive_scan``, ``transform_exclusive_scan``, ``transform_inclusive_scan``,
  ``exlusive_scan_by_segment``, and ``inclusive_scan_by_segment`` algorithms when using device policies with different
  input and output value types.
```

File: documentation/release_notes.rst [hunk 23]
```diff
@@ -11,14 +11,70 @@ creating efficient heterogeneous applications.
...
+- Improved performance of search operations (e.g., ``find``, ``all_of``, ``equal``, ``search``, etc.), ``is_heap`` and
+  ``is_heap_until`` algorithms on Intel® Arc™ B-series GPU devices.
+
+Fixed Issues
+------------
+- Removed requirement of GPU double support to use ``set_union``, ``set_difference``, ``set_intersection``, and
+  ``set_symmetric_difference`` on Windows operating systems.
+- Removed copy constructible requirements from value type for ``reduce`` and ``transform_reduce`` algorithms when used
+  with a host policy, and default constructible requirements from value type for ``reduce`` and ``transform_reduce``
+  when used with any execution policy.
```
Comment (akukanov) [inline documentation/release_notes.rst]:
```suggestion
- Removed default-constructible requirements from the value type for ``reduce`` and ``transform_reduce`` algorithms,
  as well as copy-constructible requirements when these algorithms are used with a native ("host") policy.
```

Comment (akukanov) [reply documentation/release_notes.rst]: I do not like the term "host policy" (which kind of implies existence of a "guest"/device), but finding another term is not simple. "Standard-compliant" is rather long and would not cover non-standard non-device policies if we ever add such (e.g., to choose an execution backend). "CPU [execution] policy" might be confusing because a device policy might target CPUs. "Local [execution] policy" sounds too ambiguous; same for "direct".

Would the term "native" be a good replacement for "host" in the context of algorithm execution policies? Also feel free to suggest another term if you see a good one.

File: documentation/release_notes.rst [hunk 24]
```diff
@@ -11,14 +11,70 @@ creating efficient heterogeneous applications.
...
+  combinations which do not have a SYCL known identity.
+- Improved performance of ``inclusive_scan_by_segment``, ``exclusive_scan_by_segment``, ``set_union``,
+  ``set_difference``, ``set_intersection``, and ``set_symmetric_difference`` when using device policies.
+- Improved performance of search operations (e.g., ``find``, ``all_of``, ``equal``, ``search``, etc.), ``is_heap`` and
+  ``is_heap_until`` algorithms on Intel® Arc™ B-series GPU devices.
+
+Fixed Issues
+------------
+- Removed requirement of GPU double support to use ``set_union``, ``set_difference``, ``set_intersection``, and
+  ``set_symmetric_difference`` on Windows operating systems.
```
Comment (akukanov) [inline documentation/release_notes.rst]:
```suggestion
- Removed requirement of GPU double precision support to use ``set_union``, ``set_difference``, ``set_intersection``,
  and ``set_symmetric_difference`` on Windows operating systems.
```

**Review by akukanov — COMMENTED** [review]
Some word-smithing from me. Apply at your discretion.

File: documentation/release_notes.rst (hunk 23 above)
Comment (timmiesmith) [reply documentation/release_notes.rst]: @akukanov what do you think about "CPU native policy" or "CPU exclusive policy"?  It gets to the point where it's as long as "Standard-compliant" I think, but at least moves us away from "host policy".

Comment (timmiesmith) [reply documentation/release_notes.rst]: I've given my suggestions more thought and don't like either because they're not concise enough.  I'm accepting the suggestion as is and we can move toward using "native" instead of "host" and continue using "device" to refer to policies targeting GPU.

**Review by mmichel11 — APPROVED** [review]
LGTM

File: documentation/release_notes.rst [hunk 25]
```diff
@@ -32,32 +32,29 @@ New Features
...
-  ``set_symmetric_difference`` on Windows operating systems.
-- Removed copy constructible requirements from value type for ``reduce`` and ``transform_reduce`` algorithms when used
-  with a host policy, and default constructible requirements from value type for ``reduce`` and ``transform_reduce``
-  when used with any execution policy.
-- Fixed an issue with incorrect handling of different projections by range-based ``merge``.
+- Removed requirement of GPU double precision support to use ``set_union``, ``set_difference``, ``set_intersection``,
+  and ``set_symmetric_difference`` on Windows operating systems.
+- Removed default-constructible requirements from the value type for ``reduce`` and ``transform_reduce`` algorithms,
+  as well as copy-constructible requirements when these algorithms are used with a native ("host") policy.
+- Fixed an issue with incorrect handling of different projections by ``ranges::merge``.
```
Comment (danhoeflinger) [inline documentation/release_notes.rst]:
```suggestion
- Fixed an issue with ``ranges::merge`` when projections of the two input ranges were not the same.
```

I think this or something other similar wording change is needed to make the note clear.
