### PR TITLE
Re-design the definition of `_ONEDPL_CPP20_RANGES_PRESENT` macro - fix compile error under `Clang 14.0.0`

### PR DESCRIPTION
**Pull request by SergeyKopienko**
In this PR we fix compile error under `CLang 14.0.0`

This error was introduced in the PR https://github.com/uxlfoundation/oneDPL/pull/2529 in the fix for comment https://github.com/uxlfoundation/oneDPL/pull/2529/changes#r2569418335

So the correct check should include `__clang_major__` check to to avoid `CLang` compiler versions less than `16`
 
<details>
<summary>Compile error:</summary>
/usr/bin/clang++ -DTEST_LONG_RUN=1 -O0 -g CMakeFiles/header_inclusion_order_numeric_0.pass.dir/general/header_inclusion_order_numeric_0.pass.cpp.o -o header_inclusion_order_numeric_0.pass  /localdisk/tools/inteloneapi_tbb/tbb/latest/lib/intel64/gcc4.8/libtbb_debug.so.12 
In file included from /test/general/header_inclusion_order_memory_0.pass.cpp:18:
In file included from /include/oneapi/dpl/execution:23:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/execution:32:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/pstl/glue_execution_defs.h:50:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/pstl/algorithm_impl.h:13:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/iterator:61:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_iterator_base_types.h:71:
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/iterator_concepts.h:979:13: error: no matching function for call to '__begin'
		= decltype(ranges::__cust_access::__begin(std::declval<_Tp&>()));
				   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/ranges_base.h:590:5: note: in instantiation of template type alias '__range_iter_t' requested here
	using iterator_t = std::__detail::__range_iter_t<_Tp>;
	^
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/ranges_util.h:98:43: note: in instantiation of template type alias 'iterator_t' requested here
	  data() requires contiguous_iterator<iterator_t<_Derived>>
										  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/ranges_util.h:203:29: note: in instantiation of template class 'std::ranges::view_interface<std::ranges::subrange<int *, int *, std::ranges::subrange_kind::sized>>' requested here
	class subrange : public view_interface<subrange<_It, _Sent, _Kind>>
							^
/test/general/header_inclusion_order_memory_0.pass.cpp:35:27: note: in instantiation of template class 'std::ranges::subrange<int *, int *, std::ranges::subrange_kind::sized>' requested here
	std::ranges::subrange subrange(ptr.get(), ptr.get() + n);
						  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/iterator_concepts.h:963:7: note: candidate template ignored: constraints not satisfied [with _Tp = std::ranges::subrange<int *, int *, std::ranges::subrange_kind::sized>]
	  __begin(_Tp& __t)
	  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/iterator_concepts.h:961:16: note: because 'is_array_v<std::ranges::subrange<int *, int *, std::ranges::subrange_kind::sized> >' evaluated to false
	  requires is_array_v<_Tp> || __member_begin<_Tp&> || __adl_begin<_Tp&>
			   ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/iterator_concepts.h:961:35: note: and 'std::ranges::subrange<int *, int *, std::ranges::subrange_kind::sized> &' does not satisfy '__member_begin'
	  requires is_array_v<_Tp> || __member_begin<_Tp&> || __adl_begin<_Tp&>
								  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/iterator_concepts.h:944:23: note: because '__decay_copy(__t.begin())' would be invalid: no member named 'begin' in 'std::ranges::subrange<int *, int *, std::ranges::subrange_kind::sized>'
		  { __decay_copy(__t.begin()) } -> input_or_output_iterator;
							 ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/iterator_concepts.h:961:59: note: and 'std::ranges::subrange<int *, int *, std::ranges::subrange_kind::sized> &' does not satisfy '__adl_begin'
	  requires is_array_v<_Tp> || __member_begin<_Tp&> || __adl_begin<_Tp&>
														  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/iterator_concepts.h:955:19: note: because '__decay_copy(begin(__t))' would be invalid: call to deleted function 'begin'
		  { __decay_copy(begin(__t)) } -> input_or_output_iterator;
						 ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/iterator_concepts.h:979:13: error: no matching function for call to '__begin'
		= decltype(ranges::__cust_access::__begin(std::declval<_Tp&>()));
				   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/ranges_base.h:590:5: note: in instantiation of template type alias '__range_iter_t' requested here
	using iterator_t = std::__detail::__range_iter_t<_Tp>;
	^
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/ranges_util.h:104:25: note: in instantiation of template type alias 'iterator_t' requested here
		&& contiguous_iterator<iterator_t<const _Derived>>
							   ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/ranges_util.h:203:29: note: in instantiation of template class 'std::ranges::view_interface<std::ranges::subrange<int *, int *, std::ranges::subrange_kind::sized>>' requested here
	class subrange : public view_interface<subrange<_It, _Sent, _Kind>>
							^
/test/general/header_inclusion_order_memory_0.pass.cpp:35:27: note: in instantiation of template class 'std::ranges::subrange<int *, int *, std::ranges::subrange_kind::sized>' requested here
	std::ranges::subrange subrange(ptr.get(), ptr.get() + n);
						  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/iterator_concepts.h:963:7: note: candidate template ignored: constraints not satisfied [with _Tp = const std::ranges::subrange<int *, int *, std::ranges::subrange_kind::sized>]
	  __begin(_Tp& __t)
	  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/iterator_concepts.h:961:16: note: because 'is_array_v<const std::ranges::subrange<int *, int *, std::ranges::subrange_kind::sized> >' evaluated to false
	  requires is_array_v<_Tp> || __member_begin<_Tp&> || __adl_begin<_Tp&>
			   ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/iterator_concepts.h:961:35: note: and 'const std::ranges::subrange<int *, int *, std::ranges::subrange_kind::sized> &' does not satisfy '__member_begin'
	  requires is_array_v<_Tp> || __member_begin<_Tp&> || __adl_begin<_Tp&>
								  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/iterator_concepts.h:944:23: note: because '__decay_copy(__t.begin())' would be invalid: no member named 'begin' in 'std::ranges::subrange<int *, int *, std::ranges::subrange_kind::sized>'
		  { __decay_copy(__t.begin()) } -> input_or_output_iterator;
							 ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/iterator_concepts.h:961:59: note: and 'const std::ranges::subrange<int *, int *, std::ranges::subrange_kind::sized> &' does not satisfy '__adl_begin'
	  requires is_array_v<_Tp> || __member_begin<_Tp&> || __adl_begin<_Tp&>
														  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/iterator_concepts.h:955:19: note: because '__decay_copy(begin(__t))' would be invalid: call to deleted function 'begin'
		  { __decay_copy(begin(__t)) } -> input_or_output_iterator;
						 ^
</details>

Before the PR https://github.com/uxlfoundation/oneDPL/pull/2529, the the `_ONEDPL_CPP20_RANGES_PRESENT ` macro was implemented as
```C++
// Clang 15 and older do not support range adaptors, see https://bugs.llvm.org/show_bug.cgi?id=44833
#    define _ONEDPL_CPP20_RANGES_PRESENT ((__cpp_lib_ranges >= 201911L) && !(__clang__ && __clang_major__ < 16))
```

### CODE REVIEW

File: include/oneapi/dpl/internal/version_impl.h [hunk 1]
```diff
@@ -30,10 +30,22 @@
...
+//   Clang 15 and older do not support range adaptors, see https://bugs.llvm.org/show_bug.cgi?id=44833
+#    if defined(__clang__)
+#        define _ONEDPL_CLANG_VERSION_CHECK (__clang_major__ >= 16)
+#    else
+#        define _ONEDPL_CLANG_VERSION_CHECK 1
+#    endif
+
 #    define _ONEDPL_CPP20_RANGES_PRESENT                                                                               \
-        ((__cpp_lib_ranges >= 201911L) && !(_LIBCPP_VERSION && _LIBCPP_VERSION < 16000))
+        ((__cpp_lib_ranges >= 201911L) && _ONEDPL_LIBCPP_VERSION_CHECK && _ONEDPL_CLANG_VERSION_CHECK)
```
Comment (dmitriy-sobolev) [inline include/oneapi/dpl/internal/version_impl.h]: Looking at https://bugs.llvm.org/show_bug.cgi?id=44833, I see that this is solely a compiler bug, not a library one. Hence, checking for \_\_clang\_\_ and \_\_clang\_major must be sufficient.

It seems that the check for libc++ emerged without validation based on [an assumption that it is a library bug](https://github.com/uxlfoundation/oneDPL/pull/2529#discussion_r2569418335). Let's remove this part.

Probably, the confusion is caused by the comments:
> Ranges library is available if the standard library provides it and concepts are supported
> Clang 15 and older do not support range adaptors, see https://bugs.llvm.org/show_bug.cgi?id=44833

They mention only the library, however a compiler support is also needed.

Comment (dmitriy-sobolev) [reply include/oneapi/dpl/internal/version_impl.h]: One more recommendation is to manually test icpx with -stdlib=libc++ flag on Ubuntu 22.04 to 100% ensure that the problem is in the clang++14 and not libc++14.

Comment (SergeyKopienko) [reply include/oneapi/dpl/internal/version_impl.h]: I think better just to restore the old definition:
```C++
#    define _ONEDPL_CPP20_RANGES_PRESENT ((__cpp_lib_ranges >= 201911L) && !(__clang__ && __clang_major__ < 16))
```

Comment (dmitriy-sobolev) [reply include/oneapi/dpl/internal/version_impl.h]: Thanks. I've verified that icpx based on clang21 works well on Ubuntu 22.04 and -std=libc++ flag with only \_\_clang\_\_ check. It is an indirect confirmation the compiler only check is sufficient.

P.S. I ran: `cmake -DCMAKE_CXX_COMPILER=icpx -DCMAKE_CXX_FLAGS="-std=libc++" -DCMAKE_CXX_STANDARD=20 ../oneDPL` with icpx 2025.3.

**Review by dmitriy-sobolev — DISMISSED** [review]
LGTM.

File: include/oneapi/dpl/internal/version_impl.h [hunk 2]
```diff
@@ -32,8 +32,7 @@
 #if _ONEDPL_CPP20_CONCEPTS_PRESENT
 // Ranges library is available if the standard library provides it and concepts are supported
 // Clang 15 and older do not support range adaptors, see https://bugs.llvm.org/show_bug.cgi?id=44833
-#    define _ONEDPL_CPP20_RANGES_PRESENT                                                                               \
-        ((__cpp_lib_ranges >= 201911L) && !(_LIBCPP_VERSION && _LIBCPP_VERSION < 16000))
+#    define _ONEDPL_CPP20_RANGES_PRESENT ((__cpp_lib_ranges >= 201911L) && !(__clang__ && __clang_major__ < 16))
```
Comment (akukanov) [inline include/oneapi/dpl/internal/version_impl.h:35]: If we have to check the clang version here, let then move the compiler version macros `_ONEDPL_GCC_VERSION`, `_ONEDPL_CLANG_VERSION` to this file.

Comment (SergeyKopienko) [reply include/oneapi/dpl/internal/version_impl.h:35]: Done

File: include/oneapi/dpl/internal/version_impl.h [hunk 3]
```diff
@@ -32,8 +41,7 @@
...
```
Comment (akukanov) [inline include/oneapi/dpl/internal/version_impl.h:35]:
```suggestion
#    define _ONEDPL_CPP20_RANGES_PRESENT (__cpp_lib_ranges >= 201911L && (!__clang__ || _ONEDPL_CLANG_VERSION >= 160000))
```
Not sure if this is better though.

Comment (SergeyKopienko) [reply include/oneapi/dpl/internal/version_impl.h:35]: 1) I think it's not correct because the `_ONEDPL_CLANG_VERSION` not always defined.
2) From my perspective the `__clang_major__ < 16` looks more readable than `_ONEDPL_CLANG_VERSION >= 160000`

Comment (akukanov) [reply include/oneapi/dpl/internal/version_impl.h:35]: OK, let's keep it simple. My bad - I missed that the macro would not be of much help here.

I reverted the last revision, approved and merged the patch.

Comment (SergeyKopienko) [reply include/oneapi/dpl/internal/version_impl.h:35]: ok, NP
